### ISSUE TITLE
Events spanning month-end do not show in month view

### ISSUE THREAD

**Issue by DaveNorris79** [williamtroup/Calendar.js#126]
**Describe the bug**
When a single Event (not recurring event) starts in one month and ends in another, the Event does not display in Month view. 

**To Reproduce**
1. Go to Calendar and select Month view. 
2. Add an event that starts in July and Ends in August
3. View the month July
4. The Event is displayed. 
5. Select the month August
6. The Event is not displayed

**Expected behavior**
It is expected the Event is shown in All months it covers, not just the start month. 

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome

**Additional context**
The same issue occurs when the Event spans multiple months, eg someone is on extended leave.

**Comment by williamtroup** [comment]
Thank you for report. I will take a look into this issue and aim to get a fix into the next release.

**Comment by williamtroup** [comment]
This issue has bee resolved in the latest release (v2.1.1).

Thanks for using Calendar.js, and don't forget to star and share it :)
