### ISSUE TITLE
Unable to add a new event.

### ISSUE THREAD

**Issue by shernandezp** [williamtroup/Calendar.js#135]
**Describe the bug**
The calendarJs object cannot be instantiated.
I downloaded the latest version and created a simple html in a local folder adding only the reference of calendar.js and I got
the error "Uncaught TypeError: Cannot read properties of undefined (reading 'addEvent')" when trying to add a new Event to the calendar.

**To Reproduce**
1. Create a new folder and download on it the dist folder.
2. Create an html document with the following code:

`
<!DOCTYPE html>
<html>
<body>
<head>
	<link rel="stylesheet" href="dist/calendar.js.css" />
	<script src="dist/calendar.js"></script>
</head>

<div id="calendar"></div>

<script> 
  var calendarInstance = calendarJs( "calendar", {
    manualEditingEnabled: true
    // All your options can be set here
  } );

	var event = {
      from: new Date(),
      to: new Date(),
      title: "A New Event",
      description: "A description of the event"
  };
  calendarInstance.addEvent( event );
</script>

</body>
</html>
` 

<img width="233" alt="image" src="https://github.com/williamtroup/Calendar.js/assets/13307854/bbfdbf25-8bc3-458b-aa0d-0fec8fb53df1">

5. See error in the browser console.

**Expected behavior**
calendarInstance not to be undefined and be able to add a new event.

**Screenshots**
<img width="730" alt="image" src="https://github.com/williamtroup/Calendar.js/assets/13307854/98b348b3-7ef1-4815-9c22-2be1f696129a">

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Brave, Microsoft Edge]

**Additional context**

**Comment by williamtroup** [comment]
Your HTML looks a little off.  HEAD tags are not supposed to be in the body.

I've just written this for you to get something working:

```
<!DOCTYPE html>
<html>
    <head>
        <title>Calendar.js</title>
        <link rel="stylesheet" href="../../dist/calendar.js.css" />
        <script src="../../dist/calendar.js"></script>
    </head>

    <body>
        <div id="calendar"></div>
    </body>

    <script>
        var calendarInstance = new calendarJs( "calendar", { 
            exportEventsEnabled: true, 
        } );

        document.title += " v" + calendarInstance.getVersion();

        var event = {
            from: new Date(),
            to: new Date(),
            title: "New Event",
            description: "A description of the new event"
        };

        calendarInstance.addEvent( event );
    </script>
</html>
```

Let me know how you get on.  As of now, this is something I cannot recreate.
