### ISSUE TITLE
Bulk Toggles in Options only "deselect all"

### ISSUE THREAD

**Issue by sottey** [williamtroup/Calendar.js#144]
**Describe the bug**
Checking the "Select All" checkbox deselects all items but clicking again does not reselct all.

**To Reproduce**
1. Go to 'Options'
2. Click on 'In weekdays, click on the  select all checkbox'

**Expected behavior**
With all checkboxes selected, the toggle checkbox should uncheck all. If all are unchecked, all should be selected. If only some are selected, traditionally, this would cause all to be selected.

**Desktop (please complete the following information):**
 - OS: macOs Sonoma
 - Browser Chrome
 - Version 116.0

**Comment by williamtroup** [comment]
Hi Scott,

Thanks for the bug report.  I'm having some problems recreating this bug.  I'm testing under the same conditions, and pressing "Select All" does check all the check boxes under the desired section.

There are two buttons, if you want to clear all the selections, use "Select None".

Can you send me a video of what you are seeing?

Thanks

**Comment by sottey** [comment]
I keep forgetting to mention in every single message that I am using it inside of another app. So it is probably an issue regarding that. I will troubleshoot more. 

Sorry for the churn :-(

**Comment by williamtroup** [comment]
No, it's okay, everything helps.  I will close this issue.
