### ISSUE TITLE
These fields are not provided to the translation file

### ISSUE THREAD

**Issue by ZhangChengLin** [williamtroup/Calendar.js#200]
https://github.com/williamtroup/Calendar.js/blob/ddb4e88fdb0c21dd65ea208a625ede76f208adc2/src/calendar.js#L14303-L14307

**Comment by ZhangChengLin** [comment]
In addition, there is no uniform code formatting, for example, single quotes are faster than double quotes in most cases.

**Comment by williamtroup** [comment]
Yeah, you can override them using the public functions, that's why they are not included.
