### ISSUE TITLE
The Chinese interface does not have the reading habit of adding a suffix after the date.

### ISSUE THREAD

**Issue by ZhangChengLin** [williamtroup/Calendar.js#201]
https://github.com/williamtroup/Calendar.js/blob/ddb4e88fdb0c21dd65ea208a625ede76f208adc2/src/calendar.js#L14152-L14155

These are set to a single blank character (space bar) to achieve the following style of removing the default suffix.

The interface for other languages ​​is not clear, but Chinese does not have this reading habit. I will submit a translation PR later to change the status quo.

**Comment by ZhangChengLin** [comment]
Can we omit those default holidays?
In other languages, those holidays may not be appropriate.

**Comment by williamtroup** [comment]
> Can we omit those default holidays? In other languages, those holidays may not be appropriate.

Yes, you can set the holidays manually using "addHolidays()" and "removeHolidays()".

**Comment by williamtroup** [comment]
Will be fixed in v2.10.8.

**Comment by williamtroup** [comment]
Fixed and released.
