### ISSUE TITLE
Style display error

### ISSUE THREAD

**Issue by ZhangChengLin** [williamtroup/Calendar.js#203]
https://github.com/williamtroup/Calendar.js/blob/ddb4e88fdb0c21dd65ea208a625ede76f208adc2/src/calendar.js.scss#L2565

![image](https://github.com/williamtroup/Calendar.js/assets/30773389/cd9d5a3a-d49c-49c2-9291-0831454e596b)

![image](https://github.com/williamtroup/Calendar.js/assets/30773389/4fa332b4-7372-422b-9a25-7b68c41ef228)

![image](https://github.com/williamtroup/Calendar.js/assets/30773389/2a6f2dbb-c24d-4e28-af8b-d6aebf0a7d95)

![image](https://github.com/williamtroup/Calendar.js/assets/30773389/4ca9dfea-f73c-482f-bd7d-c22f1313de22)

The previous related titles need to explicitly specify the color, or inherit the settings of some elements, but should not be inherited to the body, otherwise the text will not be visible in dark mode. 

The last one is date selection, no related buttons are displayed.

**Comment by williamtroup** [comment]
Will be fixed in the next release.
