### ISSUE TITLE
The value increases or decreases rapidly after clicking the button.

### ISSUE THREAD

**Issue by ZhangChengLin** [williamtroup/Calendar.js#207]
**Describe the bug**

**To Reproduce**

1. After clicking the up arrow, the number will automatically increase by 1
2. In the case of continuous increase, move the mouse to the down arrow, and the number will automatically decrease by 1 until it reaches the minimum value of 1
3. Only when you click on a blank space will the number stop changing.
4. The expectation should be to click once to increase a value. Rather than the current rapid increase or decrease.

**Expected behavior**

**Screenshots**
![image](https://github.com/williamtroup/Calendar.js/assets/30773389/15e9eae9-dfcc-4788-8e4f-064f0866f023)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [121.0.6167.140]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ZhangChengLin** [comment]
This may happen to all input elements of type number.

**Comment by williamtroup** [comment]
This is not related to the calendar itself, as I have reproduced it in chrome with the calendar available.

**Comment by ZhangChengLin** [comment]
https://github.com/williamtroup/Calendar.js/assets/30773389/cf55a9ef-5977-47d9-bc7b-c063907f4de4


This is a video example. 
When I was in the alarm offset input box, I only clicked the two up and down arrow buttons once. The rest of the time I moved the mouse pointer over them without clicking. But the numbers in the input box do keep changing.
