### ISSUE TITLE
The local persistence function clears fields that do not belong to the calendar.

### ISSUE THREAD

**Issue by ZhangChengLin** [williamtroup/Calendar.js#208]
https://calendar-js.com/examples/persistence.html

https://github.com/williamtroup/Calendar.js/blob/5e512588be2c71bd20c5aeb908eba917dd5a9d2c/dist/calendar.js#L7497

The problem occurs again when double-clicking the date and the edit event pops up.

When creating a new event by clicking the plus button, no problem is found or a problem occurs.

**Comment by williamtroup** [comment]
Will be fixed in v2.10.8.

**Comment by williamtroup** [comment]
Fixed and released.
