### ISSUE TITLE
Building the library

### ISSUE THREAD

**Issue by redcubie** [williamtroup/Calendar.js#225]
Please add instructions on how to build the library (generate the contents of `dist`), so local changes can be implemented.

**Comment by williamtroup** [comment]
The dist folder is made of the minimised and stripped down versions of calendar.js in src.  You can use the Closure Compiler for dist > calendar.js, and the same for calendar.min.js.

**Comment by sinavir** [comment]
Hello, thank you for your amazing work. Can you provide the exact command to generate the dist folder ?

**Comment by williamtroup** [comment]
I did use a tool for this, but it stopped working the way I wanted.

So, I use the following tools:
https://closure-compiler.appspot.com/home
https://iblogbox.com/devtools/closure/

The CSS is built automatically using the SASS watcher you ca get for VS Code.

The CSS is minimized using:

https://www.minifier.org/

Hope this helps.

Thanks
Will
