### ISSUE TITLE
Is there any way to colourize differently?

### ISSUE THREAD

**Issue by ntung** [williamtroup/Calendar.js#246]
Hello,

I am making events in different colours depending on some attributes. I would like to know if the plugin can accomplish it.
For example:
- ACCEPTED items: green
- REJECTED items: red

**Comment by williamtroup** [comment]
You can set the colours of the events using the Event Editor dialog, or you can set the colours manually on the event JSON.

The event properties you can set are here:
https://calendar-js.com/documentation/event.html

**Comment by ntung** [comment]
Thank you for your prompt reply! This option is so helpful!
I add colours when rendering all events. However, there is a bit tricky here. My colours override the gray colour covering past events. It would be better if we could retain the gray colour which is used to overlay past events but different colours can be also applied. That's the nature of the problem.

**Comment by williamtroup** [comment]
The past events only use an opacity CSS class.  You can check the CSS using the browser developer tools.
