### ISSUE TITLE
Translation for Vienamese

### ISSUE THREAD

**Issue by ntung** [williamtroup/Calendar.js#248]
Hello,

I would like to contribute to the project by translating all texts into Vietnamese. Can you guide me on how to do it? Thanks!

**Comment by william-troup** [comment]
This support in coming in the next release.

**Comment by william-troup** [comment]
Support added in v2.12.2.

**Comment by ntung** [comment]
@william-troup Thanks for supporting Vietnamese! Can I correct the translation? There are several weird translations that I guess you got from Google Translation.
