### ISSUE TITLE
ID change on updating an event

### ISSUE THREAD

**Issue by egebilecen** [williamtroup/Calendar.js#25]
It appears when I update an existing event, it will change that event's id. And old id is not passed to `onEventUpdated` event. This makes impossible to update events in the database since I have no way to get old id without some javascript shenanigans. Please add an option to enable updated events to keep their old id or just return old id as well in `onEventUpdated`.

Edit: I just added `event.old_id = id;` line to `calendarjs.js:4890` for temporary fix. But I would like to see this in original library as well.

Also, I really liked your library, thank you for working on this.

**Comment by williamtroup** [comment]
Emm, it is supposed to keep the ID the same if updating an item, so must have made a boo-boo somewhere.

Thank you, will have this fixed in the next version.

**Comment by williamtroup** [comment]
Fixed in v0.9.1.
