### ISSUE TITLE
The background color and text color of holidays stay persistent in every month

### ISSUE THREAD

**Issue by arhontis** [williamtroup/Calendar.js#258]
The background color and text color of holidays stay persistent in every month.

**To Reproduce**
1. create some test holidays with background color and text color.
2. Init and display the calendar in Month view.
3. Change to the next or previous month
4. The colors that where set on the cells of the days that used to be holidays, stay on the same cells even though the new cells (days) are not holidays after we changed month/

**Expected behavior**
The colors of the new cells should be colored as holidays when they are not.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 2.12.1

**Comment by william-troup** [comment]
Thank you for posting this issue.  I've been able to replicate the problem and will be issuing a fix in the next release.

**Comment by william-troup** [comment]
Fixed in v2.12.2.
