### ISSUE TITLE
New Event not setting date correctly.

### ISSUE THREAD

**Issue by Gfellha** [williamtroup/Calendar.js#29]
So while playing around with the program, I noticed that when using the add events (the one right in the thing, where you can right-click a cell, and click the add new events and the model pops up) I discovered is that whatever I date I inserted into the dialog, the event would always appear on the day before the day I selected. I have a set of images I'm attaching showing what I did and the outcome that comes up.

![exmaple one](https://user-images.githubusercontent.com/36118564/116745488-263d3c00-a9c9-11eb-8583-0a18c6311620.PNG)
![example two](https://user-images.githubusercontent.com/36118564/116745487-263d3c00-a9c9-11eb-88ae-d99877af149f.PNG)
![example 3](https://user-images.githubusercontent.com/36118564/116745489-263d3c00-a9c9-11eb-9d21-3e2aa41d0484.PNG)

As you can see, despite selected the sixteenth as the date, it appears on the fifteenth.

**Comment by Gfellha** [comment]
I found out what the issue was.  In the getSelectedDate function, you have result = new Date( input.value); where input.value is just the date (without the time). If you omit the time in the new Date(string) constructor, UTC time is assumed. So the displayed value is actually correct. Use new Date('2016-09-05 00:00') to create the date object in local time. so I just changed it to:
result = new Date( input.value + ' 00:00'); and now it appears on the date that is specified in the model. 

Answer is stolen from: ( https://stackoverflow.com/questions/39223481/incorrect-date-shown-in-new-date-in-javascript )

**Comment by williamtroup** [comment]
Hi there, I'm aware of this bug and it will be fixed in the next version.

Can you tell me what Locale your in and what browser you are using?

Thanks

**Comment by Gfellha** [comment]
I'm using google Chrome for my browser, and what exactly do you mean by locale exactly?

**Comment by williamtroup** [comment]
Ah sorry, tired and mis-read your comment.  Thanks again for reporting this bug.  Your fix is very similar to the one I have put in place, so you can use that fix until the next release.

Thanks again.

**Comment by williamtroup** [comment]
Should be fixed in v0.9.4.
