### ISSUE TITLE
Keeping track of events.

### ISSUE THREAD

**Issue by Gfellha** [williamtroup/Calendar.js#31]
Hello again, I do hope you're having a nice day. 

I was wondering if there was a feature or a planned feature, that would allow me to set a function to trigger on creating/deleting/editing an event, so I can keep track of new events, edited events, and deleted events, for keeping track of things when I save the events to a database. Since, as of now, it seems I need to wipe all the events, before saving a new set, and that's a little inefficient. Or I need to keep track of which events exist on the creation of the calendar, and compare them to the events when I'm saving, which feels a little round-a-bout. Either way, let me know, so I can proceed with whatever direction I need to.

**Comment by williamtroup** [comment]
If you look in the options, there are three events for handling this:

1.  onEventAdded
2. onEventUpdated
3. onEventRemoved

Thanks
