### ISSUE TITLE
Double click on 8th, then the event is created on 7th

### ISSUE THREAD

**Issue by omarruben** [williamtroup/Calendar.js#35]
great calendar, but this issue is present : 
 Double click on 8th, then the event is created on 7th
did try with other dates and the same result

**Comment by williamtroup** [comment]
Hi, can you tell me what browser you were using?

**Comment by omarruben** [comment]
Firefox 89.0.2

________________________________

**Comment by williamtroup** [comment]
What version of the library are you using?

**Comment by omarruben** [comment]
Calendar.js v0.9.7


________________________________

**Comment by williamtroup** [comment]
This will be fixed in v0.9.8, which is coming hopefully in the next week.  Thank you for reporting the problem.

**Comment by williamtroup** [comment]
v0.9.8 is now available.  Please let me know if this issue persists.

Thanks again.

**Comment by omarruben** [comment]
I downloaded the last version today and tried  again, still the same problem . I used Firefox and Chrome, even in Chrome I had the same result.
