### ISSUE TITLE
Still wrong date created, click on 8th.. the events is created on 7th

### ISSUE THREAD

**Issue by omarruben** [williamtroup/Calendar.js#37]
I downloaded the last version today and tried again, still the same problem . I used Firefox and Chrome, even in Chrome I had the same result. I did try on the cell phone, laptop, now the issue is present everywhere . Used to be only Firefox.

**Comment by williamtroup** [comment]
O, I've reverted the changes in 0.9.8a.  Can you get the latest version and send me some screen shots of the day you want to add the event to, the dialog as it appears when adding and what it looks like afterwards.

Thanks

**Comment by williamtroup** [comment]
OK, I have found the problem.  This will be addressed in the next release.

Thanks again for your patience.

This is a side project of mine and only really do it in my free time, so thank you for using it :)

**Comment by omarruben** [comment]
Thank you, I know is not an easy thing to create and it is time consuming also.

**Comment by williamtroup** [comment]
Hi.  This problem should be fixed in v0.9.9, which I've just pushed.

Thanks again for your patience.
