### ISSUE TITLE
Help: example how to call a function after event is added

### ISSUE THREAD

**Issue by omarruben** [williamtroup/Calendar.js#40]
can you please post a small example how to call a function after event is added?
I want to call a ajax function to save the current month changes on a PHP server after I created a event on the GUI , thank you

**Comment by williamtroup** [comment]
If you take a look at https://williamtroup.github.io/Calendar.js/options.html, if you scroll to the bottom, you will see a list of event that's you can attach when setting the options up.

One of these is called onEventAdded, the other is onEventsAdded. These events will be triggered and will pass the event, or events through to them for you to access.

Hope this helps.

**Comment by mbgwdev** [comment]
Hello, sorry to reopen this. How should I use "onEventsAdded" to capture the events on my script? I´ve tried many ways, all I get is that "Uncaught TypeError: calendarInstance.onEventsAdded is not a function". Thank you!
