### ISSUE TITLE
Hi again, the exports showing wrong dates

### ISSUE THREAD

**Issue by omarruben** [williamtroup/Calendar.js#43]
the exports show the wrong date by month:

    From: 10/05/2021 00:00 <----------------------------- should be 10/06/2021
    To: 10/05/2021 00:00
    Title: June-10 <----------------------------------------------------------- created with the GUI, double  click
    Description:
    Location:
    Group:
    IsAllDay: No
    Color:
    ColorText:
    ColorBorder:
    RepeatEveryExcludeDays:
    Url:
    RepeatEvery: Never
    OrganizerName: Your Name
    OrganizerEmailAddress: your@email.address
    Id: 5aa20652-f2f0-e8c7-5639-6f5e957fee9c
    Created: 19/06/2021 20:48

**Comment by williamtroup** [comment]
HI, what version of the library are you using?  Also, what timezone are you in?

**Comment by williamtroup** [comment]
Not sure what is happening here, I can understand it being one day out (which I cannot repeat at the moment), but an entire month is strange.

**Comment by williamtroup** [comment]
Oh wait ... found it, months are zero index-based.  My bad.  Will get this fixed for the next version.  That should be out later today.

Thanks again for your patience.

**Comment by williamtroup** [comment]
OK, just released v1.0.2 (was lined up anyway, so your fix is an additional item).  Thanks again and please let me know if you find anything else.
