### ISSUE TITLE
import some events

### ISSUE THREAD

**Issue by sargi** [williamtroup/Calendar.js#52]
Hello,
Can I import or add some events from JSON? And see these events still on the website?
Can I disable all buttons on header except prev and next month and months and years?
I tried several options, but do not work.

Thanks for help.

**Comment by williamtroup** [comment]
If you look in the functions list, there are 4 functions that will help you add events. You can JSON.Parse you json data and use one of those functions to add them.

I will be adding more support to disable the other buttons on the toolbar, which will be coming in a later version. I will keep you informed!

Dont forget to star and share the project if you like it :)

**Comment by williamtroup** [comment]
I've added a new setting that will disable the buttons on the main display.  This will be available in v1.3.0 when it becomes available.

Let me know if you need any more assistance.

**Comment by sargi** [comment]
Hello,
Can you help me with call events from json file? I've tried a few options, but it still doesn't work for me.
sometimes I'm a jerk :-)
I'm still learning

Thanks for help

**Comment by sargi** [comment]
Is there any way to remove holidays like April 1st and more?

**Comment by williamtroup** [comment]
Take a look at the options you can pass to the setOptions() function, this will allow you to set, or clear, the holidays, and change the test for every area to whatever you want.

**Comment by sargi** [comment]
Thank you. I hope I can do that :-)
And the previous request for help?

**Comment by williamtroup** [comment]
What do you mean by call events from JSON? Do you mean calling an event when you import some JSON?

**Comment by sargi** [comment]
Sry, I have JSON FILE with events. So can you help me with calling an events using a JSON file?
I am sorry for my English. I don't speak English very well :-D

**Comment by williamtroup** [comment]
JSON cannot contain event, its a notation format for storing data.

**Comment by sargi** [comment]
I'll try.
When I export all events to a JSON file. I have a JSON file with a list of all events. I need advice on how to use this JSON file to import these events from a JSON file into the calendar. I do not want to copy all items directly into the script in html again. Is there any way to import this or it is better to write everything directly into <script> in HTML as you have it in the example calendarjs.html?

This is one of many events from JSON file.
                {
                    from: new Date('2021-08-10T13:24:00'),
                    to: new Date('2021-08-10T15:24:00'),
                    title: "FC Jílové - FK Komárov",
                    description: "Nějaký popis.",
                    location: "Teams Meeting"
                },

**Comment by williamtroup** [comment]
You would need to upload the file using a form, read the contents of the file and then call the addEventsFromJson() on the calendar instance.
