### ISSUE TITLE
Automatic Refresh Issue

### ISSUE THREAD

**Issue by Gfellha** [williamtroup/Calendar.js#56]
Hello!

I recently updated to the newest version of Calender.js. So, I have a large amount events added onto the calendar, going back a few months since I started using it. When the autoRefreshTimer triggers a refresh, it takes a few seconds before all the events return. I noticed that even when I check off the auto-refresh, it still does the refresh, and the option ends up getting rechecked within the options display menu. (I've, for the moment, just commented out the start startAutoRefreshTimer() function).

**Comment by williamtroup** [comment]
Thank you for the feedback. I will take a look into this for the next version. What version are you currently using? 1.3.2?

**Comment by Gfellha** [comment]
Actually, I'm using 1.3.1, i hadn't even noticed that the new version come out two hours ago, haha.

**Comment by Gfellha** [comment]
The updated it to 1.3.2, and i still seem to be getting the same constant auto refresh even when I have unchecked in the menu.

**Comment by williamtroup** [comment]
OK, been able to re-create it.  Will look into it now and see if I can issue a fix.

**Comment by Gfellha** [comment]
Thanks!

**Comment by williamtroup** [comment]
I've just published v1.3.3 which should fix the problem with the auto-refresh timer not disabling.

Thank you for the feedback and please let me know if you have any issues or suggestions!

Please remember to star, follow and share the project if you are enjoying using it!
