### ISSUE TITLE
How to display bootstrap 5 modal instead of inbuilt modal

### ISSUE THREAD

**Issue by DCodeMania** [williamtroup/Calendar.js#68]
I'm working on it and wanted to implement the Bootstrap 5 modal when double click on any date, and from that modal, I'll store event in the database and then fetch and displays them in the calendar.

Can you please tell me how can I implement the bootstrap modal when the double click of any day?

**Comment by williamtroup** [comment]
Double-clicking a date in the display will load the Event Editor.  There is no custom event available for double-clicking, as this appears to be a custom trigger you want.

Take a look at the documentation for the event types you can use.

Thanks
