### ISSUE TITLE
Events getting disappeared after refreshing webpage in drupal 9

### ISSUE THREAD

**Issue by jishnuvenu** [williamtroup/Calendar.js#70]
Hello

Events are getting disappeared on every refresh of the webpage in drupal 9. Every time I creates an event , it gets disappear on refreshing/reloading the webpage. Refreshing the calendar(refresh button in calendar),is not deleting any events,. But refreshing the whole webpage deletes the events.

**Comment by jishnuvenu** [comment]
Thanks for the reply!!!

Is there any option or any update, so that calendar can store the events? It would be really helpful if  there is code or any update to store the events in calendar, so that it wont disappear on every refresh.

**Comment by williamtroup** [comment]
The Calendar stores the events internally during the life cycle of the page.  You can get all the events from the calendar and save them to an external source.  Once you have done that, you can use that external source to populate the calendar on each load.  JavaScript libraries do not store things internal between page usages unless you use Cookies, which for this, is not fit for purpose.
