### ISSUE TITLE
What kind of Event (actions) are avalaible?

### ISSUE THREAD

**Issue by Mte90** [williamtroup/Calendar.js#88]
As example holiday events have the onClick event (seems the only one that is possible to intercept).

But if I want an event to be executed on removing one or changing some details there are some events that I can use? As I need as example that those user actions execute custom code to integrate somewhere else.
I was wondering something that I can use with `addEventListener` or a global function in the CalendarJS library.

As I can see now everything executed in the calendar is just exportable as CSV/etc but I cannot intercept those user actions, in the documentation/code I don't find anything.

**Comment by williamtroup** [comment]
Go to this page:  https://williamtroup.github.io/Calendar.js/options.html

Scroll down to the "Event Options" list.  You will see a list of custom events that can be assigned and triggered when the user performs a specific action, like adding an event, removing an event, etc.

If there is something that needs to trigger that is not on that list, let me know.  I will add it to the to-do list.

Thanks

**Comment by ntung** [comment]
Thanks for raising this issue. I have the same need. Can anyone give a snippet of codes how to handle `onClick` when clicking on an event? Thank you very much.

**Comment by williamtroup** [comment]
Hi there,

You can see all the events supported here:
https://calendar-js.com/documentation/custom-triggers.html

To assign an event, use the following example:

```
var calendarInstance = new calendarJs( "myCalendar", {
  events: {
    onEventsAdded: YourJSFunction
  }
} );
```

You can also set the custom events by calling setOptions().
